export const TRAFFICABILITY_API = 'TRAFFICABILITY_API';
export const SOILWETNESS_API = 'SOILWETNESS_API';
export const SOILTEMPERATUE_API = 'OILTEMPERATUE_API';
export const SNOWHEIGHT_API = 'SNOWHEIGHT_API';
export const WINDGUST_API = 'WINDGUST_API';
export const POSITION = 'POSITION';
export const SETWMSLAYERINFORMATION = "SETWMSLAYERINFORMATION";